.TH SIMPLE_SHELL "August 2023" "simple_shell\-0.1" "man Page-user manual"
.SH NAME
simple_shell - UNIX command line interpreter
.SH SYNOPSIS
.B #include\ "simple_shell.h"

.B ./hsh [command_file [argument...]]

.SH INTERACTION EXAMPLES

.B Non-Interactive
- $ echo "ls" | ./hsh

.B Initialize Program
- $ ./shs

.B Interactive
- $ ls

.P
.SH COMPILE
 gcc -Wall -Werror -Wextra -pedantic -std=gnu89 *.c -o hsh
.SH DESCRIPTION
The simple shell utility is a command language interpreter that will execute commands read from a
command line string or the standard input. It cleans any spaces in the string to make sure all
commands will be executed and parses the commands with the text into tokens. It checks the first
token with the array of system calls available in the PATH enviroment and creates a child process
if it found a match. Once the child process completes it displays the result to the main output
and displays a new prompt for command.
.SH RETURN
 Returns "-1" on error with prompted error line message and "0" on success with new command line.
.SH BUGS
 No bugs found as of yet.
.SH AUTHOR
 Guillermo J. Pereyo & Hector J. Vazquez
.SH COPYRIGHT
.B GNU SHELL Copyright, 08/25/2023
